### ISSUE TITLE
How to add support for new keyboard?

### ISSUE THREAD

**Issue by CharleeSF** [canonical/ubuntu-frame-osk#83]
Hello,

I am using ubuntu-frame-osk for an international project and I will need support for a lot of languages.
The first one we would like to add is Korean.

How do I add support for a new language?

I spent some time researching this and found the following things:

I found [here](https://discourse.ubuntu.com/t/ubuntu-frame-osk-documentation/27568#heading--configuration--modifying-the-layout) that explains how to change a keyboard layout. This initially gave me the idea that it was possible to create/find a `ko.yaml` file and put it here and we'd have support for Korean. however, there seem to be a few things from stopping me to do this:
1. The support for keyboards seems to be hardcoded. Basically, when you use the `snap set ubuntu-frame-osk layout=` interface, the contents of layout are checked against a hardcoded list, see here: [ubuntu-frame-osk/snap/hooks/configure at main · canonical/ubuntu-frame-osk](https://github.com/canonical/ubuntu-frame-osk/blob/main/snap/hooks/configure#L10). I don’t know if this is intentional or a bug?
2. I worked around the previous issue by writing "ko" to /var/snap/ubuntu-frame-osk/current/osk-layout.txt (sidenote: I had to do this from the app's shell to have the right permissions; `sudo snap run --shell ubuntu-frame-osk.list-layouts -c 'echo ko > $SNAP_DATA/osk-layout.txt'`. This mostly worked and showed some Korean characters on my app's keyboard. However, some characters don't show correctly on the keyboard itself (see highlighted in attached image), and once I try to type into my text field none of the characters show correctly.

Is it possible to add support ourselves or do we need to wait for someone maintaining this project to do so?

![Image](https://github.com/user-attachments/assets/bf521f32-718f-488a-9cfe-e502bf5eada1)

P.S. I tried to add the yaml file but apparently yaml files are not allowed!

**Comment by Saviq** [comment]
@CharleeSF thanks for the detailed report!

On attaching YAML, you could've just inlined it:

~~~
```yaml
content:
  here: ""
```
~~~

---

On using custom layouts, I think we could do something like `snap set ubuntu-frame-osk layout custom:ko,custom:xx,...` that wouldn't get verified with the built-in layouts.

---

About the characters being wrong, that's going to be a font issue - the fonts used / available don't have the required glyphs. On the OSK side, that's something we can work on (can you confirm which snap track you're using? the snap uses the Yaru themes, with the Ubuntu font, it might be necessary to allow overriding that - testing with the `squeekboard` package could be easier) - but on the app side, that's going to be in your app's snap. You have to make sure to include and use fonts that have those glyphs.

---

One way or another, it would be best to submit any new layouts upstream:

https://gitlab.gnome.org/World/Phosh/squeekboard/-/tree/main/data/keyboards

We can then pull them into the snap, or you could use the "custom" mechanism above.

**Comment by aliihsancengiz** [comment]
@Saviq thanks for the quick response, we have tried to use the existing layouts, like Bulgarian, Arabic, etc, seems like our application is rendering well, as we typed we can see characters, but it's not possible to use the backspace for deleting characters.

Do you think this is also related to fonts, or there could be some other issues too?

Here is some logs

```
2025-02-03T13:50:01Z systemd[1]: Started Service for snap application ubuntu-frame-osk.daemon.
2025-02-03T13:50:01Z ubuntu-frame-osk.daemon[30303]: Setting input sources to [('xkb', 'bg')]
2025-02-03T13:50:01Z ubuntu-frame-osk.daemon[30303]: Debug: Tried file "/var/snap/ubuntu-frame-osk/common/squeekboard/keyboards/bg.yaml", but it's missing: No such file or directory (os error 2)
2025-02-03T13:50:01Z ubuntu-frame-osk.daemon[30303]: Info: Loaded layout Resource: bg
2025-02-03T13:50:01Z ubuntu-frame-osk.daemon[30303]: Debug: Tried file "/var/snap/ubuntu-frame-osk/common/squeekboard/keyboards/bg.yaml", but it's missing: No such file or directory (os error 2)
2025-02-03T13:50:01Z ubuntu-frame-osk.daemon[30303]: Info: Loaded layout Resource: bg
2025-02-03T13:50:01Z -[30303]: Could not connect to session manager: Cannot autolaunch D-Bus without X11 $DISPLAY

2025-02-03T13:50:01Z -[30303]: Failed to init libfeedback: Cannot autolaunch D-Bus without X11 $DISPLAY
2025-02-03T13:50:01Z ubuntu-frame-osk.daemon[30303]: Can't connect to the bus: Cannot autolaunch D-Bus without X11 $DISPLAY. Visibility switching unavailable.Debug: Tried file "/var/snap/ubuntu-frame-osk/common/squeekboard/keyboards/bg_wide.yaml", but it's missing: No such file or directory (os error 2)
2025-02-03T13:50:01Z ubuntu-frame-osk.daemon[30303]: Warning: Failed to load layout from Resource: bg_wide: Missing resource, skipping
2025-02-03T13:50:01Z ubuntu-frame-osk.daemon[30303]: Debug: Tried file "/var/snap/ubuntu-frame-osk/common/squeekboard/keyboards/bg.yaml", but it's missing: No such file or directory (os error 2)
2025-02-03T13:50:01Z ubuntu-frame-osk.daemon[30303]: Info: Loaded layout Resource: bg


```

**Comment by CharleeSF** [comment]
Hey there,

For not being able to set custom keyboards I think the `layout=custom:ko` option sounds good to me. Then at least it is easy to try out new yaml files on the fly. I do see the value of adding them upstream however.

Then for the font issues, there is missing characters in both the keyboard and the application.

For the application I am in the process of testing with a different font.
However, how do I control the font on the keyboard to display those characters correctly? And how do I know what supports what?

The yaml I made is incomplete, but the one I made to show the image I posted is this. The 5th characters on the keyboard (this one for example: 쇼) are not displaying the same on the keyboard as they are in the YAML.

```
# Language: Korean
---
outlines:
    default:        { width: 32.415,  height: 52 }
    change-view:    { width: 32.415,  height: 52 }
    change-view-2:  { width: 64.83,   height: 52 }
    fill:           { width: 64.83,   height: 52 }
    large:          { width: 35.656,  height: 52 }
    spaceline:      { width: 90.763,  height: 52 }
    spaceline-fill: { width: 155.593, height: 52 }
    special:        { width: 32.415,  height: 52 }
    special-2:      { width: 35.656,  height: 52 }
    special-3:      { width: 64.83,   height: 52 }

views:
    base:
        - "ㅂ ㅈ ㄷ ㄱ 쇼 ㅕ ㅑ ㅐ ㅔ"
        - "ㅁ ㄴ ㅇ ㄹ 호 ㅓ ㅏ ㅣ"
        - "show_upper ㅋ ㅌ ㅊ 퓨 ㅜ ㅡ BackSpace"
        - "show_numbers preferences ё space , . Return"
    upper:
        - "ㅃ ㅉ ㄸ ㄲ 쑈 ㅕ ㅑ ㅒ ㅖ"
        - "ㅁ ㄴ ㅇ ㄹ 호 ㅓ ㅏ ㅣ"
        - "show_upper ㅋ ㅌ ㅊ 퓨 ㅜ ㅡ BackSpace"
        - "show_numbers preferences space , . Return"
    numbers:
        - "1 2 3 4 5 6 7 8 9 0"
        - "@ # $ % & - _ + ( )"
        - "show_symbols , \" ' : ; ! ? BackSpace-wide"
        - "show_letters preferences space-fill . Return"
    symbols:
        - "~ ` | · √ π τ ÷ × ¶ ²"
        - "© ® £ € ¥ ^ ° * { } ³"
        - "show_numbers \\ / < > = [ ] BackSpace-wide"
        - "show_letters preferences space-fill . Return"

buttons:
    show_upper:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "change-view"
        icon: "key-shift"
    BackSpace:
        outline: "special"
        icon: "edit-clear-symbolic"
        action: "erase"
    BackSpace-wide:
        outline: "special-3"
        icon: "edit-clear-symbolic"
        action: "erase"
    preferences:
        action: "show_prefs"
        outline: "special-2"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "change-view-2"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "change-view-2"
        label: "АБВ"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "change-view-2"
        label: "*/="
    .:
        outline: "large"
    space:
        outline: "spaceline"
        text: " "
    space-fill:
        outline: "spaceline-fill"
        text: " "
    Return:
        outline: "special-3"
        icon: "key-enter"
        keysym: "Return"

```
